defaults:
  poll_interval_seconds: 3600
  max_tweets_per_run: 5

models:
  reply_model: gpt-5-mini
  classifier_model: gpt-5-nano

personas:
  official_bot:
    reply_prompt_path: prompts/official_bot/reply.md
    classifier_prompt_path: prompts/classifier.txt
  eve_bot:
    reply_prompt_path: prompts/eve_bot/reply.md
    classifier_prompt_path: prompts/classifier.txt

groups:
  - persona: official_bot
    accounts:
      - handle: punkstrategys
        access_token: "eUN6aWxsVGdRcXVrNHdyM2lXTE5Wdkx5d2xGWGdIT1NzT3QtMVVZX2pucm1HOjE3NjA5NzY4OTAwNTQ6MToxOmF0OjE"
        refresh_token: "SUtmZ0lRbHRjdHhNeWduTUNVaDc3X0R4bjM2NXQ2aEg5cERFR0dndkJWVHVuOjE3NjA5NzY4OTAwNTQ6MTowOnJ0OjE"
        search_query: '("PunkStrategy" OR "$PNKSTR" OR "PunkStrategyStrategy" OR "PNKSTR") (lang:en OR lang:und)'

  - persona: eve_bot
    accounts:
      - handle: EveZero_42
        access_token: "TDBvamNmR0lFUER0OWIzLWg1bGxMbVlYblVHa0RfWGNqT2Y2dXBZbW5wUDRTOjE3NjA5NzkxMjM4MTU6MTowOmF0OjE"
        refresh_token: "MFZaSndFZmhhcE9ZdDlTbTJJQm1yaTE4WHlzWndadlZoRVhMaWVueU5mX0FJOjE3NjA5NzkxMjM4MTU6MTowOnJ0OjE"
        search_query: '("PunkStrategy" OR "$PNKSTR" OR "PunkStrategyStrategy" OR "PNKSTR") (lang:en OR lang:und)'

bots:
  ignore_handles:
    - punkstrategys
    - EveZero_42
