[profile.default]
src = "src"
out = "out"
libs = ["lib"]

auto_detect_solc = true
evm_version = "cancun"
optimizer = true
optimizer_runs = 200
via_ir = true
remappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "@uniswap/v4-core/=lib/v4-core/",
  "@uniswap/v4-periphery/=lib/v4-periphery/",
  "@v4/=lib/v4-core/",
  "v4-router/=lib/v4-router/src/",
  "permit2/=lib/permit2/",
  "@permit2/=lib/permit2/src/",
  "solady/=lib/solady/src/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
