name: Deploy

on:
  push:
    branches: [main]

jobs:
  build_publish_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/post
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}

      - name: Deploy to server
        if: ${{ secrets.SSH_HOST && secrets.SSH_USER && secrets.SSH_KEY }}
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            IMAGE="${{ env.IMAGE_NAME }}:latest"
            docker login ghcr.io -u "${{ github.repository_owner }}" -p "${{ secrets.GHCR_TOKEN }}"
            docker pull "$IMAGE"
            cd /srv/post
            IMAGE="$IMAGE" docker compose up -d
